probe_interval: 15s # Time between checking the domain

domains:
  - name: finza.finance
    providers:
      - name: Cloudflare # Provider (make sure the name is well put)
        time_per_probe: 3s # Time to wait for a response from a probe
  - name: app.finza.finance
    providers:
      - name: Cloudflare # Provider (make sure the name is well put)
        time_per_probe: 3s # Time to wait for a response from a probe
  - name: api.finza.finance
    providers:
      - name: Cloudflare # Provider (make sure the name is well put)
        time_per_probe: 3s # Time to wait for a response from a probe
