probe_interval: 15s

provider:
  - name: Cloudflare
    time_per_probe: 3s
    capabilities:
      - proxy_toggle
    domains:
      - finza.finance
      - app.finza.finance
      - api.finza.finance
